### ISSUE TITLE
windows build

### ISSUE THREAD

**Issue by stefanschneider** [cloudfoundry-incubator/executor#8]
Can we make a PR to remove "syscall.SIGUSR1" from https://github.com/cloudfoundry-incubator/executor/blob/master/main.go#L175 ?

Removing that signal would make it available for a windows build. 

Rep and Converger are not using USR1 signal, so I guess it doesn't provide any extra functionality for executor. See:
https://github.com/cloudfoundry-incubator/converger/blob/master/main.go#L82
https://github.com/cloudfoundry-incubator/rep/blob/master/main.go#L132

**Comment by ematpl** [comment]
Hi, @stefanschneider, 

I'm closing out this issue. As it turns out, we didn't user USR1 or USR2 signal handling for the rep's evacuation after all. Our Garden Windows team now even has the rep and executor functioning on Windows, co-located with their [garden-windows](https://github.com/cloudfoundry-incubator/garden-windows) implementation.

Thanks,
Eric, for the CF Runtime Diego team
